"""Generate assets/constellation.svg — the agent roster as the Lyra star map.

The six core stars follow the real Lyra constellation geometry used in the
hero mark; four satellites extend the chart. Node styling reflects each
agent's status in data/agents.json (live / paused / planned) so the plate
stays truthful when regenerated by CI.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
import lyra_type
from lyra_plates import PAL, footer, open_plate, title_band

ROOT = Path(__file__).parent.parent
W, H = 1200, 620

# name -> (star x, star y, label anchor, label x, label y, core star?)
LAYOUT = {
    "Solaris": (600, 190, "middle", 600, 140, True),
    "Atlas":   (535, 275, "end",    513, 270, True),
    "Nova":    (668, 285, "start",  690, 280, True),
    "Kai":     (520, 415, "end",    498, 410, True),
    "Volt":    (692, 415, "start",  714, 410, True),
    "Aria":    (600, 500, "middle", 600, 532, True),
    "Blaze":   (300, 250, "end",    278, 245, False),
    "Mizu":    (900, 250, "start",  922, 245, False),
    "Frost":   (330, 470, "end",    308, 465, False),
    "Rex":     (880, 480, "start",  902, 475, False),
}

CORE_LINES = [("Solaris", "Atlas"), ("Solaris", "Nova"), ("Atlas", "Nova"),
              ("Atlas", "Kai"), ("Nova", "Volt"), ("Kai", "Volt"),
              ("Kai", "Aria"), ("Volt", "Aria")]
SATELLITE_LINES = [("Blaze", "Atlas"), ("Mizu", "Nova"),
                   ("Frost", "Kai"), ("Rex", "Volt")]

# faint background stars, fixed so the chart is deterministic
FIELD_STARS = [(120, 120, 1.4), (210, 340, 1.1), (160, 520, 1.3), (420, 150, 1.0),
               (455, 555, 1.2), (760, 140, 1.1), (795, 545, 1.3), (1000, 350, 1.4),
               (1060, 150, 1.0), (1085, 500, 1.2), (620, 320, 0.9), (390, 320, 1.0),
               (860, 350, 1.0), (240, 430, 0.9)]


def node(name: str, status: str) -> str:
    x, y, _, _, _, core = LAYOUT[name]
    r_star = 6.5 if name == "Solaris" else 4.5 if core else 4.0
    parts = []
    if name == "Solaris":
        parts.append(f'<circle cx="{x}" cy="{y}" r="26" fill="url(#const-glow)"/>')
    if status == "planned":
        parts.append(f'<circle cx="{x}" cy="{y}" r="{r_star + 0.5}" fill="none" '
                     f'stroke="{PAL["gold"]}" stroke-width="1.3" stroke-dasharray="2.5 2.5"/>')
    elif status == "paused":
        parts.append(f'<circle cx="{x}" cy="{y}" r="{r_star}" fill="{PAL["gold"]}" fill-opacity="0.35"/>')
    else:
        parts.append(f'<circle cx="{x}" cy="{y}" r="{r_star}" fill="{PAL["gold"]}"/>')
    return "\n  ".join(parts)


def label(name: str, role: str, status: str) -> str:
    _, _, anchor, lx, ly, _ = LAYOUT[name]
    dim = status != "live"
    name_fill = PAL["soft"] if dim else PAL["ink"]
    parts = [
        lyra_type.svg_text(name.upper(), lx, ly, "mono", "regular", 13,
                           name_fill, letter_spacing=2.5, anchor=anchor),
        lyra_type.svg_text(role, lx, ly + 17, "serif", "italic", 12.5,
                           PAL["soft"] if dim else PAL["mut"], anchor=anchor),
    ]
    if status != "live":
        parts.append(lyra_type.svg_text(status.upper(), lx, ly + 35, "mono",
                                        "regular", 8.5, PAL["bronze"],
                                        letter_spacing=1.7, anchor=anchor))
    return "\n  ".join(parts)


def main() -> None:
    data = json.loads((ROOT / "data" / "agents.json").read_text(encoding="utf-8"))
    agents = {a["name"]: a for a in data["agents"] if a["name"] in LAYOUT}

    n_live = sum(1 for a in agents.values() if a["status"] == "live")
    n_other = len(agents) - n_live
    right = f"{n_live} LIVE · {n_other} PLANNED" if n_other else f"{n_live} LIVE"
    if data.get("updated"):
        right += f" · AS OF {data['updated'][:10]}"

    svg = [open_plate(W, H, "const")]
    svg.append("  " + title_band(
        W, "LYRA SYSTEMS · AGENT ROSTER", "The constellation",
        "Ten agents, each with its own book and its own rules.", right))

    for x, y, r in FIELD_STARS:
        svg.append(f'  <circle cx="{x}" cy="{y}" r="{r}" fill="{PAL["gold"]}" fill-opacity="0.15"/>')

    for a, b in CORE_LINES:
        xa, ya = LAYOUT[a][:2]
        xb, yb = LAYOUT[b][:2]
        svg.append(f'  <line x1="{xa}" y1="{ya}" x2="{xb}" y2="{yb}" '
                   f'stroke="{PAL["gold"]}" stroke-width="1.2" stroke-opacity="0.5" stroke-linecap="round"/>')
    for a, b in SATELLITE_LINES:
        xa, ya = LAYOUT[a][:2]
        xb, yb = LAYOUT[b][:2]
        svg.append(f'  <line x1="{xa}" y1="{ya}" x2="{xb}" y2="{yb}" '
                   f'stroke="{PAL["gold"]}" stroke-width="1" stroke-opacity="0.3" stroke-dasharray="2 4"/>')

    for name in LAYOUT:
        agent = agents.get(name)
        if not agent:
            continue
        svg.append("  " + node(name, agent["status"]))
        svg.append("  " + label(name, agent["role"], agent["status"]))

    svg.append("  " + footer(W, H, "TEN BOOKS · ONE REGISTER · STATUS SYNCS FROM THE OPERATOR LOG"))
    svg.append("</svg>\n")

    out = ROOT / "assets" / "constellation.svg"
    out.write_text("\n".join(svg), encoding="utf-8")
    print(f"wrote {out.relative_to(ROOT)} ({n_live} live, {n_other} planned/paused)")


if __name__ == "__main__":
    main()
